### PR TITLE
Fixed some typos and grammatical mistakes until chapter 4

### PR DESCRIPTION
**Pull request by sinaebrahimi**
I have read the excellent book with scrutiny, and I thought I could make it better by correcting some typos. 

I have some doubts about my understanding of P4 (Section 4.4.3). In commit c84e29abc159d1d5056ead1e4801474c4cdf7bf1 (line 17 correct me if I'm wrong or misunderstood!), I changed "hdr.ethernet.srcAddr = hdr.ethernet.dstAddr;" since I guessed it was a typo. 

I am genuinely grateful to Larry Paterson and the team for sharing this superior SDN knowledge in a relatively easy chronological order.

Best regards, 
Sina

### CODE REVIEW

**Comment by llpeterson** [comment]
Thanks for these corrections. Almost all of them are good, but a couple need attention.
1) The line "This complexity use to..." should stay as is, and not change to "This complexity used to..."
2) Line 17 was correct: Since this node is forwarding, it becomes the sender of the packet it just received.

**Comment by sinaebrahimi** [comment]
Thank you very much.

I corrected the two mistakes you mentioned.

**Comment by llpeterson** [comment]
Thanks!

**Comment by sinaebrahimi** [comment]
You're welcome.

Thanks for all the quality work you have done in the field of networking. I grew my interest in networking when I was a bachelor's student and studied your "Computer Networks: Systems Approach" back then (~2014).

Then, when I was doing research projects about SDN, all the work you had done in ONF seemed extraordinary to me, and now I am working in the industry to foster SDN in hybrid/traditional routers.

I appreciate all the work you and your teammates have done through these years.


Kind regards,
Sina

**Pull request merged**
